spring.application.name=autofind
server.port=8081
spring.datasource.url=jdbc:h2:file:./autofind-db;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.thymeleaf.cache=false
server.error.include-message=never
